# Generated by Django 4.0.3 on 2022-04-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], max_length=20, null=True)),
                ('edad', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], max_length=20, null=True),
        ),
    ]
