# Generated by Django 4.0.3 on 2022-04-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_mascotas_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascotas',
            options={'verbose_name_plural': 'mascotas'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='sexo',
        ),
    ]
