# Generated by Django 4.0.3 on 2022-04-15 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_mascotas_options_rename_quantity_product_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_rescate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 15, 17, 29, 52, 201561, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
