# Generated by Django 4.0.3 on 2022-04-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_fecha_rescate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fecha_rescate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
