# Generated by Django 4.0.3 on 2022-04-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_product_fecha_rescate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Profile_Images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fecha_rescate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de rescate: (DD/MM/AA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
