# Generated by Django 4.0.3 on 2022-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_product_image_alter_product_fecha_rescate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='especie',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
