# Generated by Django 4.0.3 on 2022-04-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_product_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razones_para_adoptar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='telefono',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
