# Generated by Django 4.0.3 on 2022-04-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_order_direccion_order_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='edad',
            new_name='edad_solicitante',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='nombre_de_mascota',
        ),
    ]
