# Generated by Django 4.0.3 on 2022-05-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_edad_order_edad_solicitante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nombre_de_mascota',
        ),
    ]
