# Generated by Django 4.0.3 on 2022-05-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_vacunas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacunas',
            options={'verbose_name_plural': 'Vacuna'},
        ),
    ]
