# Generated by Django 4.0.3 on 2022-05-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_vacunas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacunas',
            options={'verbose_name_plural': 'Vacunas'},
        ),
    ]
