# Generated by Django 4.0.3 on 2022-05-04 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_vacunas_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacunas',
            new_name='Vacuna',
        ),
    ]
