# Generated by Django 4.0.3 on 2022-05-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_vacunas_vacuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Product_Images'),
        ),
    ]
